# Generated by Django 5.1.5 on 2025-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
