# Generated by Django 5.1.5 on 2025-02-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='category',
            field=models.CharField(choices=[('FICTION', 'fiction'), ('HORROR', 'horror'), ('SCFI', 'scfi'), ('SPLATTER', 'splatter'), ('FANTASY', 'fantasy')], default='FICTION', max_length=50),
        ),
    ]
