# Generated by Django 5.1.5 on 2025-02-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_mybook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='year',
            field=models.IntegerField(),
        ),
    ]
