# Generated by Django 5.1.5 on 2025-02-11 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app01', '0003_paydeliver_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paydeliver',
            name='cvv',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='paydeliver',
            name='expiry_month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='paydeliver',
            name='expiry_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
