# Generated by Django 5.1.5 on 2025-02-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app01', '0004_alter_paydeliver_cvv_alter_paydeliver_expiry_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_deliver',
        ),
    ]
