# Generated by Django 5.1.5 on 2025-02-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app01', '0005_rename_payment_order_payment_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app01.paydeliver'),
        ),
    ]
