# Generated by Django 5.1.5 on 2025-02-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app01', '0006_alter_order_payment_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paydeliver',
            name='address2',
        ),
    ]
