# Generated by Django 5.1.5 on 2025-02-13 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app01', '0007_remove_paydeliver_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paydeliver',
            old_name='address1',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='paydeliver',
            name='expiry_month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Valid months are 1-12'), django.core.validators.MaxValueValidator(12, 'Valid months are 1-12')]),
        ),
        migrations.AlterField(
            model_name='paydeliver',
            name='expiry_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025, 'Valid years are 2025-9999'), django.core.validators.MaxValueValidator(9999, 'Valid years are 2025-9999')]),
        ),
    ]
