# Generated by Django 5.1.5 on 2025-02-13 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app01', '0008_rename_address1_paydeliver_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paydeliver',
            old_name='fname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='paydeliver',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'CVV must be 3 digits')]),
        ),
    ]
